GET http://localhost:3001 HTTP/1.1

################

GET http://localhost:3001/api/persons HTTP/1.1

################

GET http://localhost:3001/api/info HTTP/1.1

################

GET http://localhost:3001/api/person/1 HTTP/1.1